name: Linty
description: A dead simple linter where you write your tests in good ol' Javascript
inputs:
  go-version:
    description: "The Go version to use"
    required: true
    default: "1.21.4"
  node-version:
    description: "The Node.js version to use"
    required: true
    default: "18"
  config-path:
    description: "The path to the configuration and JavaScript files"
    required: true
    default: ".github/workflows/linty"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download linty.go from abcdan/linty
      run: |
        curl -o linty.go https://raw.githubusercontent.com/abcdan/linty/main/linty.go
      shell: bash

    - name: Download linty.js from abcdan/linty
      run: |
        curl -o linty.js https://raw.githubusercontent.com/abcdan/linty/main/linty.js
      shell: bash

    - name: Download LINTYCHECK from abcdan/linty
      run: |
        curl -o LINTYCHECK https://raw.githubusercontent.com/abcdan/linty/main/LINTYCHECK
      shell: bash

    - name: Download go.mod from abcdan/linty
      run: |
        curl -o go.mod https://raw.githubusercontent.com/abcdan/linty/main/go.mod
      shell: bash

    - name: Download go.sum from abcdan/linty
      run: |
        curl -o go.sum https://raw.githubusercontent.com/abcdan/linty/main/go.sum
      shell: bash

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Pull Go dependencies
      run: go mod tidy
      shell: bash

    - name: Run Linty
      run: go run linty.go ${{ inputs.config-path }}
      shell: bash
